from fpdf import FPDF
import io

class GrowthHubPDF(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 16)
        self.set_text_color(0, 86, 179)
        self.cell(0, 10, "GrowthHub AI - Official Academic & Career Record", 0, 1, "C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 9)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} - Generated by GrowthHub AI", 0, 0, "C")

def generate_roadmap_pdf(target_career: str, degree_program: str, description: str) -> bytes:
    pdf = GrowthHubPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(33, 33, 33)
    pdf.cell(0, 10, f"Career Roadmap: {target_career}", 0, 1, "L")
    
    pdf.set_font("helvetica", "", 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Target Degree Program: {degree_program}", 0, 1, "L")
    pdf.ln(5)
    
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, "I. Core Competency & Milestone Summary", 0, 1, "L")
    
    pdf.set_font("helvetica", "", 11)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 6, description)
    pdf.ln(10)
    
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, "II. Recommended Execution Phases", 0, 1, "L")
    
    phases = [
        "A. Foundational Skill Acquisition & Technical Depth",
        "B. Capstone Portfolio Development & Open Source Contributions",
        "C. Advanced Internship Targeting & Interview Preparation"
    ]
    
    pdf.set_font("helvetica", "", 11)
    for phase in phases:
        pdf.cell(0, 6, phase, 0, 1, "L")
        
    pdf_output = pdf.output(dest="S")
    return bytes(pdf_output)