"""Add engineering columns to portfolios

Revision ID: 3c0bb2eafe2f
Revises: 309c8daa1ab8
Create Date: 2026-07-28 22:37:59.501734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c0bb2eafe2f'
down_revision: Union[str, Sequence[str], None] = '309c8daa1ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_roadmaps_id'), table_name='career_roadmaps')
    op.drop_table('career_roadmaps')
    op.drop_index(op.f('ix_finance_articles_id'), table_name='finance_articles')
    op.drop_table('finance_articles')
    op.drop_index(op.f('ix_resume_reviews_id'), table_name='resume_reviews')
    op.drop_table('resume_reviews')
    op.add_column('chat_history', sa.Column('sender_role', sa.String(), nullable=False))
    op.add_column('chat_history', sa.Column('message', sa.Text(), nullable=False))
    op.add_column('chat_history', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('chat_history', 'user_prompt')
    op.drop_column('chat_history', 'created_at')
    op.drop_column('chat_history', 'ai_response')
    op.add_column('portfolios', sa.Column('project_title', sa.String(), nullable=False))
    op.add_column('portfolios', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('portfolios', sa.Column('github_url', sa.String(), nullable=True))
    op.add_column('portfolios', sa.Column('research_paper_link', sa.String(), nullable=True))
    op.add_column('portfolios', sa.Column('tech_stack', sa.String(), nullable=True))
    op.create_index(op.f('ix_portfolios_project_title'), 'portfolios', ['project_title'], unique=False)
    op.drop_column('portfolios', 'quantity')
    op.drop_column('portfolios', 'created_at')
    op.drop_column('portfolios', 'asset_name')
    op.drop_column('portfolios', 'buy_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('buy_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('portfolios', sa.Column('asset_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('portfolios', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('portfolios', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_portfolios_project_title'), table_name='portfolios')
    op.drop_column('portfolios', 'tech_stack')
    op.drop_column('portfolios', 'research_paper_link')
    op.drop_column('portfolios', 'github_url')
    op.drop_column('portfolios', 'description')
    op.drop_column('portfolios', 'project_title')
    op.add_column('chat_history', sa.Column('ai_response', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('chat_history', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('chat_history', sa.Column('user_prompt', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('chat_history', 'timestamp')
    op.drop_column('chat_history', 'message')
    op.drop_column('chat_history', 'sender_role')
    op.create_table('resume_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ats_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('resume_reviews_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('resume_reviews_pkey'))
    )
    op.create_index(op.f('ix_resume_reviews_id'), 'resume_reviews', ['id'], unique=False)
    op.create_table('finance_articles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('finance_articles_pkey'))
    )
    op.create_index(op.f('ix_finance_articles_id'), 'finance_articles', ['id'], unique=False)
    op.create_table('career_roadmaps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_role', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('roadmap_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('career_roadmaps_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('career_roadmaps_pkey'))
    )
    op.create_index(op.f('ix_career_roadmaps_id'), 'career_roadmaps', ['id'], unique=False)
    # ### end Alembic commands ###
